### ISSUE TITLE
mix nerves_hub.user auth failed, may be related to pbcs 0.1.3

### ISSUE THREAD

**Issue by pojiro** [nerves-hub/nerves_hub_cli#179]
This phenomenon may be related to pbcs 0.1.3. Because getting it back to 0.1.2 this doesn't occur.

```
$ asdf current 
elixir          1.11.2-otp-23   /home/pojiro/.tool-versions
erlang          23.3.4          /home/pojiro/.tool-versions
```

Below is the error log, nerves_hub_cli and pbcs version are printed in

```
$ mix nerves_hub.user auth
NervesHub server: api.nerves-hub.org:443
Username or email address: pojiro
NervesHub password: 
Authenticating...
Success

NervesHub uses client-side SSL certificates to authenticate CLI requests.

The next step will create an SSL certificate and store it in your 
'/home/pojiro/.nerves-hub' directory. A password is required to protect it. This password
does not need to be your NervesHub password. It will never be sent to NervesHub
or any other computer. If you lose it, you will need to run
'mix nerves_hub.user auth' and create a new certificate.

Please enter a local password: 
** (ArgumentError) argument error
    :erlang.iolist_to_binary({<<...>>, "-----BEGIN EC PRIVATE KEY-----\n...\n-----END EC PRIVATE KEY-----\n\n"})
    (crypto 4.9) crypto.erl:1404: :crypto.crypto_one_time/5
    (pbcs 0.1.3) lib/pbcs.ex:28: PBCS.encrypt/3
    (nerves_hub_cli 0.11.1) lib/nerves_hub_cli/user.ex:17: NervesHubCLI.User.save_certs/3
    (nerves_hub_cli 0.11.1) lib/mix/tasks/nerves_hub.user.ex:223: Mix.Tasks.NervesHub.User.generate_certificate/3
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

As other info, nerves_hub_cli with pbcs 0.1.2 still has a weird behavior, like below. 

```
iex(3)> PBCS.decrypt({"", encrypted_priv}, password: password)
:error
iex(4)> PBCS.decrypt({"", encrypted_priv}, password: password)
:error
iex(5)> PBCS.decrypt({"", encrypted_priv}, password: password)
:error
iex(6)> PBCS.decrypt({"", encrypted_priv}, password: password)
:error
iex(7)> NervesHubCLI.Crypto.decrypt(encrypted_priv, password)
{:ok, "decrypted_priv"}
iex(8)> PBCS.decrypt({"", encrypted_priv}, password: password)
{:ok, "decrypted_priv"}
```

Once invoke from `NervesHubCLI.Crypto.decrypt`, `PBCS.decrypt` wil be ok. (I cannot understand why this happens)
see. https://github.com/nerves-hub/nerves_hub_cli/blob/main/lib/nerves_hub_cli/crypto.ex

With pbcs 0.1.3 this never return {:ok, "decrypted_priv"}, like below.

```
iex(3)> PBCS.decrypt({"", encrypted_priv}, password: password)
:error
iex(4)> PBCS.decrypt({"", encrypted_priv}, password: password)
:error
iex(5)> PBCS.decrypt({"", encrypted_priv}, password: password)
:error
iex(6)> NervesHubCLI.Crypto.decrypt(encrypted_priv, password)
{:error, "unknown"}
iex(7)> NervesHubCLI.Crypto.decrypt(encrypted_priv, password)
{:error, "unknown"}
iex(8)> NervesHubCLI.Crypto.decrypt(encrypted_priv, password)
{:error, "unknown"}
```

Please let me know if you need any other information. Thank you.

**Comment by fhunleth** [comment]
I can confirm that `pbcs 0.1.3` doesn't work and that I'm getting similar errors to you. I have not debugged.

**Comment by pojiro** [comment]
I can confirm nerves_hub_cli works with [`pbcs 0.1.4`](https://github.com/hexpm/pbcs/blob/5446d4602f4638046f2dcafd7ae0359866e0da42/CHANGELOG.md#v014) (fixed version of this issue).

And the weird behavior of  `pbcs 0.1.2`  I reported was seemed my mistake, I confirm `pbcs 0.1.2` works well.

So this issue can be closed. Thank you @mobileoverlord and @fhunleth .

**Comment by fhunleth** [comment]
Thanks for confirming that it works for you!
