### ISSUE TITLE
Allow suplying org from `config.exs`

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_cli#61]
According to [the docs on `nerves_hub`](https://github.com/nerves-hub/nerves_hub#creating-nerveshub-firmware-signing-keys) if one doesn't use the default org created with Nerves-Hub

```
config :nerves_hub,
  public_keys: [:prod, :staging, :"staging-2"]
```
You get a error:

```
== Compilation error in file lib/nerves_hub/certificate.ex ==
** (Mix.Error) NervesHub is unable to find key: :prod
    (mix) lib/mix.ex:323: Mix.raise/1
    lib/nerves_hub_cli.ex:27: anonymous fn/3 in NervesHubCLI.public_keys/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/nerves_hub/certificate.ex:3: (module)
```

**Comment by ConnorRigby** [comment]
There are existing ways to do this. Read the docs and found it. Sorry for the noise.
